name: Deploy Frontend
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Adjust path to the Dockerfile inside the new folder
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f frontend-gh-actions/Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test

      # Zip the deployment package from the new folder
      - name: Generate deployment package
        run: zip -r deploy.zip ./frontend-gh-actions -x '*.git*'

      # Use the updated deployment package path
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: docker-gh
          environment_name: Dockergh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: frontend-gh-actions/deploy.zip

